from airflow.utils.session import provide_session as provide_session
from typing import ClassVar

TYPE_CHECKING: bool
NEW_SESSION: None

class BaseJobRunner:
    job_type: ClassVar[str] = ...
    def __init__(self, job: Job) -> None: ...
    def heartbeat_callback(self, *args, **kwargs) -> None: ...
    @classmethod
    def most_recent_job(cls, *args, **kwargs) -> Job | JobPydantic | None: ...
