import airflow.models.baseoperator
from airflow.models.baseoperator import BaseOperator as BaseOperator
from airflow.utils.email import send_email as send_email
from typing import ClassVar

TYPE_CHECKING: bool

class EmailOperator(airflow.models.baseoperator.BaseOperator):
    template_fields: ClassVar[tuple] = ...
    template_fields_renderers: ClassVar[dict] = ...
    template_ext: ClassVar[tuple] = ...
    ui_color: ClassVar[str] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def execute(self, context: Context): ...
