import airflow.models.baseoperator
from airflow.models.baseoperator import BaseOperator as BaseOperator
from typing import ClassVar

TYPE_CHECKING: bool

class SmoothOperator(airflow.models.baseoperator.BaseOperator):
    ui_color: ClassVar[str] = ...
    yt_link: ClassVar[str] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def execute(self, context: Context): ...
