from _typeshed import Incomplete
from airflow.decorators import task as task, task_group as task_group
from airflow.models.dag import DAG as DAG

def task_start(): ...
def task_1(value: int) -> str: ...
def task_2(value: str) -> str: ...
def task_3(value: str) -> None: ...
def task_end() -> None: ...
def task_group_function(value: int) -> None: ...

start_task: Incomplete
end_task: Incomplete
current_task_group: Incomplete
