from _typeshed import Incomplete
from airflow.decorators import setup as setup, task as task, task_group as task_group, teardown as teardown
from airflow.models.dag import DAG as DAG

def my_first_task() -> None: ...
def my_second_task() -> None: ...
def my_third_task() -> None: ...

task_1: Incomplete
task_2: Incomplete
task_3: Incomplete

def outer_setup(): ...
def outer_teardown(cluster_id) -> None: ...
def outer_work() -> None: ...
def section_1(): ...
