from airflow.models.dag import DAG as DAG, dag as dag
from airflow.operators.python import PythonOperator as PythonOperator, extract_task as extract_task, load_task as load_task, transform_task as transform_task

def extract(**kwargs): ...
def transform(**kwargs): ...
def load(**kwargs): ...
