from airflow.configuration import conf as conf
from airflow.exceptions import AirflowConfigException as AirflowConfigException

TYPE_CHECKING: bool
auth_manager: None
def get_auth_manager_cls() -> type[BaseAuthManager]: ...
def init_auth_manager(appbuilder: AirflowAppBuilder) -> BaseAuthManager: ...
def get_auth_manager() -> BaseAuthManager: ...
