from airflow.configuration import conf as conf
from airflow.exceptions import AirflowConfigException as AirflowConfigException, AirflowException as AirflowException
from airflow.www.extensions.init_auth_manager import get_auth_manager as get_auth_manager

def init_xframe_protection(app): ...
def init_api_experimental_auth(app): ...
def init_check_user_active(app): ...
