import airflow.triggers.base
import airflow.utils.timezone as timezone
import datetime
from airflow.triggers.base import BaseTrigger as BaseTrigger, TriggerEvent as TriggerEvent
from typing import Any, ClassVar

class DateTimeTrigger(airflow.triggers.base.BaseTrigger):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, moment: datetime.datetime) -> None: ...
    def serialize(self) -> tuple[str, dict[str, Any]]: ...
    def run(self): ...

class TimeDeltaTrigger(DateTimeTrigger):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, delta: datetime.timedelta) -> None: ...
