from _typeshed import Incomplete
from airflow.cli.simple_table import AirflowConsole as AirflowConsole
from airflow.cli.utils import is_stdout as is_stdout, print_export_output as print_export_output
from airflow.compat.functools import cache as cache
from airflow.configuration import conf as conf
from airflow.exceptions import AirflowNotFoundException as AirflowNotFoundException
from airflow.hooks.base import BaseHook as BaseHook
from airflow.models import Connection as Connection
from airflow.providers_manager import ProvidersManager as ProvidersManager
from airflow.secrets.local_filesystem import load_connections_dict as load_connections_dict
from airflow.utils import helpers as helpers, yaml as yaml
from airflow.utils.cli import suppress_logs_and_warning as suppress_logs_and_warning
from airflow.utils.providers_configuration_loader import providers_configuration_loaded as providers_configuration_loaded
from airflow.utils.session import create_session as create_session

def connections_get(args) -> None: ...
def connections_list(args) -> None: ...
def create_default_connections(args) -> None: ...
def connections_export(args) -> None: ...

alternative_conn_specs: Incomplete

def connections_add(args) -> None: ...
def connections_delete(args) -> None: ...
def connections_import(args) -> None: ...
def connections_test(args) -> None: ...
