from _typeshed import Incomplete
from airflow import settings as settings
from airflow.api_internal.internal_api_call import InternalApiConfig as InternalApiConfig
from airflow.exceptions import AirflowException as AirflowException
from airflow.utils import db as db
from airflow.utils.db_cleanup import config_dict as config_dict, drop_archived_tables as drop_archived_tables, export_archived_records as export_archived_records, run_cleanup as run_cleanup
from airflow.utils.process_utils import execute_interactive as execute_interactive
from airflow.utils.providers_configuration_loader import providers_configuration_loaded as providers_configuration_loaded
from tenacity import RetryCallState as RetryCallState

log: Incomplete

def initdb(args) -> None: ...
def resetdb(args) -> None: ...
def upgradedb(args) -> None: ...
def get_version_revision(version: str, recursion_limit: int = 10) -> str | None: ...
def migratedb(args) -> None: ...
def downgrade(args) -> None: ...
def check_migrations(args) -> None: ...
def shell(args) -> None: ...
def check(args) -> None: ...

all_tables: Incomplete

def cleanup_tables(args) -> None: ...
def export_archived(args) -> None: ...
def drop_archived(args) -> None: ...
