from airflow.cli.simple_table import AirflowConsole as AirflowConsole
from airflow.providers_manager import ProvidersManager as ProvidersManager
from airflow.utils.cli import suppress_logs_and_warning as suppress_logs_and_warning
from airflow.utils.providers_configuration_loader import providers_configuration_loaded as providers_configuration_loaded

ERROR_IMPORTING_HOOK: str

def provider_get(args) -> None: ...
def providers_list(args): ...
def hooks_list(args): ...
def triggers_list(args): ...
def notifications_list(args): ...
def connection_form_widget_list(args): ...
def connection_field_behaviours(args): ...
def extra_links_list(args): ...
def logging_list(args): ...
def secrets_backends_list(args): ...
def auth_backend_list(args): ...
def auth_managers_list(args): ...
def executors_list(args): ...
def config_list(args): ...
def lazy_loaded(args) -> None: ...
