from airflow.cli.simple_table import AirflowConsole as AirflowConsole
from airflow.cli.utils import print_export_output as print_export_output
from airflow.models import Variable as Variable
from airflow.utils.cli import suppress_logs_and_warning as suppress_logs_and_warning
from airflow.utils.providers_configuration_loader import providers_configuration_loaded as providers_configuration_loaded
from airflow.utils.session import create_session as create_session, provide_session as provide_session

def variables_list(args): ...
def variables_get(args) -> None: ...
def variables_set(args) -> None: ...
def variables_delete(args) -> None: ...
def variables_import(args, session) -> None: ...
def variables_export(args) -> None: ...
