import airflow.template.templater
import jinja2
from airflow.template.templater import Templater as Templater
from airflow.utils.context import context_merge as context_merge
from typing import ClassVar

TYPE_CHECKING: bool

class BaseNotifier(airflow.template.templater.Templater):
    template_fields: ClassVar[tuple] = ...
    template_ext: ClassVar[tuple] = ...
    def __init__(self) -> None: ...
    def render_template_fields(self, context: Context, jinja_env: jinja2.Environment | None = ...) -> None: ...
    def notify(self, context: Context) -> None: ...
    def __call__(self, *args) -> None: ...
