import airflow.utils.timezone as timezone
import flask_appbuilder.forms
import flask_wtf.form
import functools
import wtforms.fields.core
import wtforms.widgets.core
from _typeshed import Incomplete
from airflow.configuration import conf as conf
from airflow.providers_manager import ProvidersManager as ProvidersManager
from airflow.utils.types import DagRunType as DagRunType
from airflow.www.validators import ReadOnly as ReadOnly, ValidConnID as ValidConnID
from airflow.www.widgets import AirflowDateTimePickerROWidget as AirflowDateTimePickerROWidget, AirflowDateTimePickerWidget as AirflowDateTimePickerWidget, BS3TextAreaROWidget as BS3TextAreaROWidget, BS3TextFieldROWidget as BS3TextFieldROWidget
from typing import ClassVar

class DateTimeWithTimezoneField(wtforms.fields.core.Field):
    widget: ClassVar[wtforms.widgets.core.TextInput] = ...
    def __init__(self, label: Incomplete | None = ..., validators: Incomplete | None = ..., datetime_format: str = ..., **kwargs) -> None: ...
    def process_formdata(self, valuelist): ...

class DateTimeForm(flask_wtf.form.FlaskForm):
    execution_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    _unbound_fields: ClassVar[None] = ...
    _wtforms_meta: ClassVar[None] = ...

class DateTimeWithNumRunsForm(flask_wtf.form.FlaskForm):
    base_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    num_runs: ClassVar[wtforms.fields.core.UnboundField] = ...
    _unbound_fields: ClassVar[None] = ...
    _wtforms_meta: ClassVar[None] = ...

class DagRunEditForm(flask_appbuilder.forms.DynamicForm):
    dag_id: ClassVar[wtforms.fields.core.UnboundField] = ...
    start_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    end_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    run_id: ClassVar[wtforms.fields.core.UnboundField] = ...
    state: ClassVar[wtforms.fields.core.UnboundField] = ...
    execution_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    conf: ClassVar[wtforms.fields.core.UnboundField] = ...
    note: ClassVar[wtforms.fields.core.UnboundField] = ...
    _unbound_fields: ClassVar[None] = ...
    _wtforms_meta: ClassVar[None] = ...
    def populate_obj(self, item): ...

class TaskInstanceEditForm(flask_appbuilder.forms.DynamicForm):
    dag_id: ClassVar[wtforms.fields.core.UnboundField] = ...
    task_id: ClassVar[wtforms.fields.core.UnboundField] = ...
    start_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    end_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    state: ClassVar[wtforms.fields.core.UnboundField] = ...
    execution_date: ClassVar[wtforms.fields.core.UnboundField] = ...
    note: ClassVar[wtforms.fields.core.UnboundField] = ...
    _unbound_fields: ClassVar[None] = ...
    _wtforms_meta: ClassVar[None] = ...
    def populate_obj(self, item): ...
create_connection_form_class: functools._lru_cache_wrapper
