from flask.sessions import SecureCookieSessionInterface
from flask_session.sessions import SqlAlchemySessionInterface

class SessionExemptMixin:
    def save_session(self, *args, **kwargs): ...

class AirflowDatabaseSessionInterface(SessionExemptMixin, SqlAlchemySessionInterface): ...
class AirflowSecureCookieSessionInterface(SessionExemptMixin, SecureCookieSessionInterface): ...
