from _typeshed import Incomplete
from airflow.plugins_manager import integrate_listener_plugins as integrate_listener_plugins
from pluggy._hooks import _HookRelay

log: Incomplete

class ListenerManager:
    pm: Incomplete
    def __init__(self) -> None: ...
    @property
    def has_listeners(self) -> bool: ...
    @property
    def hook(self) -> _HookRelay: ...
    def add_listener(self, listener) -> None: ...
    def clear(self) -> None: ...

def get_listener_manager() -> ListenerManager: ...
