TYPE_CHECKING: bool
def on_task_instance_running(previous_state: TaskInstanceState, task_instance: TaskInstance, session): ...
def on_task_instance_success(previous_state: TaskInstanceState, task_instance: TaskInstance, session): ...
def on_task_instance_failed(previous_state: TaskInstanceState, task_instance: TaskInstance, session): ...
def on_dag_run_success(dag_run: DagRun, msg: str): ...
def on_dag_run_failed(dag_run: DagRun, msg: str): ...
def on_dag_run_running(dag_run: DagRun, msg: str): ...
