import airflow.utils.cli as cli_utils
import collections
import functools
import marshmallow.schema
from airflow.auth.managers.fab.cli_commands.utils import get_application_builder as get_application_builder
from airflow.cli.simple_table import AirflowConsole as AirflowConsole
from airflow.cli.utils import print_export_output as print_export_output
from airflow.utils.cli import suppress_logs_and_warning as suppress_logs_and_warning
from airflow.utils.providers_configuration_loader import providers_configuration_loaded as providers_configuration_loaded
from typing import ClassVar

class UserSchema(marshmallow.schema.Schema):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    opts: ClassVar[marshmallow.schema.SchemaOpts] = ...
    _declared_fields: ClassVar[dict] = ...
    _hooks: ClassVar[collections.defaultdict] = ...
def users_list(*args, **kwargs): ...
def users_create(*args, **kwargs): ...
def users_delete(*args, **kwargs): ...
def users_manage_role(*args, **kwargs): ...
def users_export(*args, **kwargs): ...
def users_import(*args, **kwargs): ...

add_role: functools.partial
remove_role: functools.partial
