from typing import ClassVar as _ClassVar

TYPE_CHECKING: bool

class BaseOperatorLink:
    operators: _ClassVar[list] = ...
    __abstractmethods__: _ClassVar[frozenset] = ...
    _abc_impl: _ClassVar[_abc_data] = ...
    __attrs_attrs__: _ClassVar[BaseOperatorLinkAttributes] = ...
    def get_link(self, operator: BaseOperator) -> str: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def name(self): ...
