from typing import NamedTuple

class TaskInstanceKey(NamedTuple):
    dag_id: str
    task_id: str
    run_id: str
    try_number: int = ...
    map_index: int = ...
    @property
    def primary(self) -> tuple[str, str, str, int]: ...
    @property
    def reduced(self) -> TaskInstanceKey: ...
    def with_try_number(self, try_number: int) -> TaskInstanceKey: ...
    @property
    def key(self) -> TaskInstanceKey: ...
    @classmethod
    def from_dict(cls, dictionary): ...
