from _typeshed import Incomplete
from airflow.hooks.base import BaseHook as BaseHook
from typing import Any

class FSHook(BaseHook):
    conn_name_attr: str
    default_conn_name: str
    conn_type: str
    hook_name: str
    @classmethod
    def get_connection_form_widgets(cls) -> dict[str, Any]: ...
    @classmethod
    def get_ui_field_behaviour(cls) -> dict[str, Any]: ...
    basepath: Incomplete
    conn: Incomplete
    def __init__(self, fs_conn_id: str = ..., **kwargs) -> None: ...
    def get_conn(self) -> None: ...
    def get_path(self) -> str: ...
    def test_connection(self): ...
