import airflow.hooks.base
from airflow.hooks.base import BaseHook as BaseHook
from typing import Any, ClassVar

class PackageIndexHook(airflow.hooks.base.BaseHook):
    conn_name_attr: ClassVar[str] = ...
    default_conn_name: ClassVar[str] = ...
    conn_type: ClassVar[str] = ...
    hook_name: ClassVar[str] = ...
    def __init__(self, pi_conn_id: str = ..., **kwargs) -> None: ...
    @staticmethod
    def get_ui_field_behaviour() -> dict[str, Any]: ...
    def get_conn(self) -> Any: ...
    def get_connection_url(self) -> Any: ...
    def test_connection(self) -> tuple[bool, str]: ...
