from _typeshed import Incomplete
from typing import TypedDict

RESOURCE_ACTION: str
RESOURCE_ADMIN_MENU: str
RESOURCE_AUDIT_LOG: str
RESOURCE_BROWSE_MENU: str
RESOURCE_CONFIG: str
RESOURCE_CONNECTION: str
RESOURCE_DAG: str
RESOURCE_DAG_CODE: str
RESOURCE_DAG_DEPENDENCIES: str
RESOURCE_DAG_PREFIX: str
RESOURCE_DAG_RUN: str
RESOURCE_DAG_RUN_PREFIX: str
RESOURCE_DAG_WARNING: str
RESOURCE_CLUSTER_ACTIVITY: str
RESOURCE_DATASET: str
RESOURCE_DOCS: str
RESOURCE_DOCS_MENU: str
RESOURCE_IMPORT_ERROR: str
RESOURCE_JOB: str
RESOURCE_MY_PASSWORD: str
RESOURCE_MY_PROFILE: str
RESOURCE_PASSWORD: str
RESOURCE_PERMISSION: str
RESOURCE_PLUGIN: str
RESOURCE_POOL: str
RESOURCE_PROVIDER: str
RESOURCE_RESOURCE: str
RESOURCE_ROLE: str
RESOURCE_SLA_MISS: str
RESOURCE_TASK_INSTANCE: str
RESOURCE_TASK_LOG: str
RESOURCE_TASK_RESCHEDULE: str
RESOURCE_TRIGGER: str
RESOURCE_USER: str
RESOURCE_USER_STATS_CHART: str
RESOURCE_VARIABLE: str
RESOURCE_WEBSITE: str
RESOURCE_XCOM: str
ACTION_CAN_CREATE: str
ACTION_CAN_READ: str
ACTION_CAN_EDIT: str
ACTION_CAN_DELETE: str
ACTION_CAN_ACCESS_MENU: str
DEPRECATED_ACTION_CAN_DAG_READ: str
DEPRECATED_ACTION_CAN_DAG_EDIT: str

class ResourceDetails(TypedDict):
    actions: set[str]
    prefix: str

DAG_ACTIONS: Incomplete
RESOURCE_DETAILS_MAP: Incomplete
PREFIX_LIST: Incomplete
PREFIX_RESOURCES_MAP: Incomplete

def resource_name(root_dag_id: str, resource: str) -> str: ...
def resource_name_for_dag(root_dag_id: str) -> str: ...
