from _typeshed import Incomplete
from airflow.utils.net import get_hostname as get_hostname

def get_components(principal) -> list[str] | None: ...
def replace_hostname_pattern(components, host: Incomplete | None = None): ...
def get_fqdn(hostname_or_ip: Incomplete | None = None): ...
def principal_from_username(username, realm): ...
