from airflow.configuration import conf as conf
from airflow.metrics.protocols import Timer as Timer
from airflow.metrics.validators import AllowListValidator as AllowListValidator, BlockListValidator as BlockListValidator, validate_stat as validate_stat

TYPE_CHECKING: bool

class SafeDogStatsdLogger:
    def __init__(self, dogstatsd_client: DogStatsd, metrics_validator: ListValidator = ..., metrics_tags: bool = ..., metric_tags_validator: ListValidator = ...) -> None: ...
    def incr(self, stat: str = ..., *args, **kwargs) -> None: ...
    def decr(self, stat: str = ..., *args, **kwargs) -> None: ...
    def gauge(self, stat: str = ..., *args, **kwargs) -> None: ...
    def timing(self, stat: str = ..., *args, **kwargs) -> None: ...
    def timer(self, stat: str | None = ..., *args, **kwargs) -> TimerProtocol: ...
def get_dogstatsd_logger(cls) -> SafeDogStatsdLogger: ...
