from _typeshed import Incomplete

revision: str
down_revision: str
branch_labels: Incomplete
depends_on: Incomplete
airflow_version: str

def upgrade() -> None: ...
def downgrade() -> None: ...
def get_table_constraints(conn, table_name) -> dict[tuple[str, str], list[str]]: ...
def reorder_columns(columns): ...
def drop_constraint(operator, constraint_dict) -> None: ...
def create_constraint(operator, constraint_dict) -> None: ...
def modify_execution_date_with_constraint(conn, batch_operator, table_name, type_, nullable) -> None: ...
