revision: str
down_revision: str
branch_labels: None
depends_on: None
airflow_version: str
def upgrade(): ...
def downgrade(): ...
def get_table_constraints(conn, table_name) -> dict[tuple[str, str], list[str]]: ...
def reorder_columns(columns): ...
def drop_constraint(operator, constraint_dict): ...
def create_constraint(operator, constraint_dict): ...
def modify_execution_date_with_constraint(conn, batch_operator, table_name, type_, nullable) -> None: ...
