revision: str
down_revision: str
branch_labels: None
depends_on: None
airflow_version: str
def get_table_constraints(conn, table_name) -> dict[tuple[str, str], list[str]]: ...
def drop_column_constraints(operator, column_name, constraint_dict): ...
def create_constraints(operator, column_name, constraint_dict): ...
def upgrade(): ...
def downgrade(): ...
