from _typeshed import Incomplete
from airflow import settings as settings
from airflow.providers.fab.auth_manager.models import Action as Action, Permission as Permission, Resource as Resource
from airflow.security import permissions as permissions

revision: str
down_revision: str
branch_labels: Incomplete
depends_on: Incomplete
airflow_version: str

def prefix_individual_dag_permissions(session) -> None: ...
def remove_prefix_in_individual_dag_permissions(session) -> None: ...
def get_or_create_dag_resource(session): ...
def get_or_create_all_dag_resource(session): ...
def get_or_create_action(session, action_name): ...
def get_resource_query(session, resource_name): ...
def get_action_query(session, action_name): ...
def get_permission_with_action_query(session, action): ...
def get_permission_with_resource_query(session, resource): ...
def update_permission_action(session, permission_query, action) -> None: ...
def get_permission(session, resource, action): ...
def update_permission_resource(session, permission_query, resource) -> None: ...
def migrate_to_new_dag_permissions(db) -> None: ...
def undo_migrate_to_new_dag_permissions(session) -> None: ...
def upgrade() -> None: ...
def downgrade() -> None: ...
