import airflow.security.permissions as permissions
import airflow.settings as settings
from airflow.auth.managers.fab.models import Action as Action, Permission as Permission, Resource as Resource

revision: str
down_revision: str
branch_labels: None
depends_on: None
airflow_version: str
def prefix_individual_dag_permissions(session): ...
def remove_prefix_in_individual_dag_permissions(session): ...
def get_or_create_dag_resource(session): ...
def get_or_create_all_dag_resource(session): ...
def get_or_create_action(session, action_name): ...
def get_resource_query(session, resource_name): ...
def get_action_query(session, action_name): ...
def get_permission_with_action_query(session, action): ...
def get_permission_with_resource_query(session, resource): ...
def update_permission_action(session, permission_query, action): ...
def get_permission(session, resource, action): ...
def update_permission_resource(session, permission_query, resource): ...
def migrate_to_new_dag_permissions(db): ...
def undo_migrate_to_new_dag_permissions(session): ...
def upgrade(): ...
def downgrade(): ...
