import abc
import k8s
from typing import ClassVar

TYPE_CHECKING: bool

class K8SModel(abc.ABC):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def attach_to_pod(self, pod: k8s.V1Pod) -> k8s.V1Pod: ...
def append_to_pod(pod: k8s.V1Pod, k8s_objects: list[K8SModel] | None): ...
