import io
from typing import Collection

TYPE_CHECKING: bool

class CliConflictError(Exception): ...
def is_stdout(fileio: IOBase) -> bool: ...
def print_export_output(command_type: str, exported_items: Collection, file: io.TextIOWrapper): ...
