from _typeshed import Incomplete
from airflow import models as models
from airflow.api.common.experimental.get_code import get_code as get_code
from airflow.api.common.experimental.get_dag_run_state import get_dag_run_state as get_dag_run_state
from airflow.api.common.experimental.get_dag_runs import get_dag_runs as get_dag_runs
from airflow.api.common.experimental.get_task import get_task as get_task
from airflow.api.common.experimental.get_task_instance import get_task_instance as get_task_instance
from airflow.exceptions import AirflowException as AirflowException
from airflow.utils import timezone as timezone
from airflow.utils.docs import get_docs_url as get_docs_url
from airflow.utils.strings import to_boolean as to_boolean
from airflow.version import version as version
from flask import Response as Response
from typing import Callable, TypeVar

log: Incomplete
T = TypeVar('T', bound=Callable)

def requires_authentication(function: T): ...

api_experimental: Incomplete

def add_deprecation_headers(response: Response): ...
def trigger_dag(dag_id): ...
def delete_dag(dag_id): ...
def dag_runs(dag_id): ...
def test(): ...
def info(): ...
def get_dag_code(dag_id): ...
def task_info(dag_id, task_id): ...
def dag_paused(dag_id, paused): ...
def dag_is_paused(dag_id): ...
def task_instance_info(dag_id, execution_date, task_id): ...
def dag_run_status(dag_id, execution_date): ...
def latest_dag_runs(): ...
def get_pool(name): ...
def get_pools(): ...
def create_pool(): ...
def delete_pool(name): ...
def get_lineage(dag_id: str, execution_date: str): ...
