import airflow.models.slamiss
import collections
import marshmallow_sqlalchemy.schema
from airflow.models.slamiss import SlaMiss as SlaMiss
from typing import ClassVar

class SlaMissSchema(marshmallow_sqlalchemy.schema.SQLAlchemySchema):
    class Meta:
        model: ClassVar[type[airflow.models.slamiss.SlaMiss]] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    opts: ClassVar[marshmallow_sqlalchemy.schema.SQLAlchemySchemaOpts] = ...
    _declared_fields: ClassVar[dict] = ...
    _hooks: ClassVar[collections.defaultdict] = ...
