import types
from _typeshed import Incomplete
from airflow.decorators.python import python_task as python_task
from airflow.exceptions import AirflowException as AirflowException
from airflow.models.baseoperator import BaseOperator as BaseOperator
from airflow.utils.setup_teardown import SetupTeardownContext as SetupTeardownContext
from typing import Callable

TYPE_CHECKING: bool
def setup_task(func: Callable) -> Callable: ...
def teardown_task(_func: Incomplete | None = ...) -> Callable: ...

class ContextWrapper(list):
    def __init__(self, tasks: list[BaseOperator | XComArg]) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...

class context_wrapper(list):
    def __init__(self, tasks: list[BaseOperator | XComArg]) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...
