import airflow.sensors.base
from airflow.exceptions import AirflowFailException as AirflowFailException
from airflow.sensors.base import BaseSensorOperator as BaseSensorOperator
from typing import ClassVar

PIPE: int
STDOUT: int
TYPE_CHECKING: bool

class BashSensor(airflow.sensors.base.BaseSensorOperator):
    template_fields: ClassVar[tuple] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def poke(self, context: Context): ...
