import airflow.sensors.base
from airflow.hooks.filesystem import FSHook as FSHook
from airflow.sensors.base import BaseSensorOperator as BaseSensorOperator
from typing import ClassVar

TYPE_CHECKING: bool

class FileSensor(airflow.sensors.base.BaseSensorOperator):
    template_fields: ClassVar[tuple] = ...
    ui_color: ClassVar[str] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def poke(self, context: Context): ...
