import httpx
from _typeshed import Incomplete

class Client:
    def __init__(self, api_base_url, auth: Incomplete | None = None, session: httpx.Client | None = None) -> None: ...
    def trigger_dag(self, dag_id, run_id: Incomplete | None = None, conf: Incomplete | None = None, execution_date: Incomplete | None = None, replace_microseconds: bool = True) -> None: ...
    def delete_dag(self, dag_id) -> None: ...
    def get_pool(self, name) -> None: ...
    def get_pools(self) -> None: ...
    def create_pool(self, name, slots, description, include_deferred) -> None: ...
    def delete_pool(self, name) -> None: ...
    def get_lineage(self, dag_id: str, execution_date: str): ...
