from _typeshed import Incomplete
from airflow.api.client import api_client as api_client

class Client(api_client.Client):
    def trigger_dag(self, dag_id, run_id: Incomplete | None = None, conf: Incomplete | None = None, execution_date: Incomplete | None = None, replace_microseconds: bool = True): ...
    def delete_dag(self, dag_id: str): ...
    def get_pool(self, name: str): ...
    def get_pools(self): ...
    def create_pool(self, name: str, slots: int, description: str, include_deferred: bool): ...
    def delete_pool(self, name: str): ...
    def get_lineage(self, dag_id: str, execution_date: str): ...
