from _typeshed import Incomplete
from airflow.api_internal.internal_api_call import internal_api_call as internal_api_call
from airflow.utils.session import NEW_SESSION as NEW_SESSION, provide_session as provide_session
from sqlalchemy.orm import Session as Session

logger: Incomplete

def register_pre_exec_callback(action_logger) -> None: ...
def register_post_exec_callback(action_logger) -> None: ...
def on_pre_execution(**kwargs) -> None: ...
def on_post_execution(**kwargs) -> None: ...
def default_action_log(sub_command, user, task_id, dag_id, execution_date, host_name, full_command, **_) -> None: ...
