def register_pre_exec_callback(action_logger): ...
def register_post_exec_callback(action_logger): ...
def on_pre_execution(**kwargs): ...
def on_post_execution(**kwargs): ...
def default_action_log(sub_command, user, task_id, dag_id, execution_date, host_name, full_command, **_): ...
