from typing import Any

def get_python_source(x: Any) -> str | None: ...
def prepare_code_snippet(file_path: str, line_no: int, context_lines_count: int = 5) -> str: ...
def get_terminal_formatter(**opts): ...
