from _typeshed import Incomplete
from typing import ClassVar

class AirflowParsingContext(tuple):
    _fields: ClassVar[tuple] = ...
    _field_defaults: ClassVar[dict] = ...
    _fields_defaults: ClassVar[dict] = ...
    _field_types: ClassVar[dict] = ...
    dag_id: Incomplete
    task_id: Incomplete
    def __init__(self, _cls, dag_id: str | None, task_id: str | None) -> None: ...
    def __getnewargs__(self): ...
def get_parsing_context() -> AirflowParsingContext: ...
