from _typeshed import Incomplete
from airflow.exceptions import RemovedInAirflow3Warning as RemovedInAirflow3Warning
from typing import Callable, TypeVar

T = TypeVar('T', bound=Callable)

def apply_defaults(func: T) -> T: ...
def remove_task_decorator(python_source: str, task_decorator_name: str) -> str: ...

class _autostacklevel_warn:
    warnings: Incomplete
    def __init__(self) -> None: ...
    def __getattr__(self, name): ...
    def __dir__(self): ...
    def warn(self, message, category: Incomplete | None = None, stacklevel: int = 1, source: Incomplete | None = None) -> None: ...

def fixup_decorator_warning_stack(func) -> None: ...
