def getattr_with_deprecation(imports: dict[str, str], module: str, override_deprecated_classes: dict[str, str], extra_message: str, name: str): ...
def add_deprecated_classes(module_imports: dict[str, dict[str, str]], package: str, override_deprecated_classes: dict[str, dict[str, str]] | None = None, extra_message: str | None = None): ...
