import airflow.models.taskmixin
from airflow.models.taskmixin import DAGNode as DAGNode, DependencyMixin as DependencyMixin
from airflow.utils.task_group import TaskGroup as TaskGroup
from typing import Sequence

class EdgeModifier(airflow.models.taskmixin.DependencyMixin):
    def __init__(self, label: str | None = ...) -> None: ...
    def set_upstream(self, other: DependencyMixin | Sequence[DependencyMixin], edge_modifier: EdgeModifier | None = ...): ...
    def set_downstream(self, other: DependencyMixin | Sequence[DependencyMixin], edge_modifier: EdgeModifier | None = ...): ...
    def update_relative(self, other: DependencyMixin, upstream: bool = ..., edge_modifier: EdgeModifier | None = ...) -> None: ...
    def add_edge_info(self, dag, upstream_id: str, downstream_id: str): ...
    @property
    def roots(self): ...
    @property
    def leaves(self): ...
def Label(label: str): ...
