from typing import Any

class JWTSigner:
    def __init__(self, secret_key: str, expiration_time_in_seconds: int, audience: str, leeway_in_seconds: int = ..., algorithm: str = ...) -> None: ...
    def generate_signed_token(self, extra_payload: dict[str, Any]) -> str: ...
    def verify_token(self, token: str) -> dict[str, Any]: ...
