import typing
from airflow.configuration import conf as conf

class MultiprocessingStartMethodMixin: ...

class ResolveMixin:
    def iter_references(self) -> typing.Iterable[tuple[Operator, str]]: ...
    def resolve(self, context: Context) -> typing.Any: ...
