from airflow.configuration import conf as conf
from airflow.exceptions import AirflowException as AirflowException

MB: int
GB: int
TB: int
PB: int
EB: int

class Resource:
    def __init__(self, name, units_str, qty) -> None: ...
    def __eq__(self, other) -> bool: ...
    def to_dict(self): ...
    @property
    def name(self): ...
    @property
    def units_str(self): ...
    @property
    def qty(self): ...

class CpuResource(Resource):
    def __init__(self, qty) -> None: ...

class RamResource(Resource):
    def __init__(self, qty) -> None: ...

class DiskResource(Resource):
    def __init__(self, qty) -> None: ...

class GpuResource(Resource):
    def __init__(self, qty) -> None: ...

class Resources:
    def __init__(self, cpus: int = ..., ram: int = ..., disk: int = ..., gpus: int = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, resources_dict: dict): ...
