from _typeshed import Incomplete
from airflow.configuration import conf as conf
from airflow.exceptions import AirflowException as AirflowException

MB: int
GB: Incomplete
TB: Incomplete
PB: Incomplete
EB: Incomplete

class Resource:
    def __init__(self, name, units_str, qty) -> None: ...
    def __eq__(self, other): ...
    @property
    def name(self): ...
    @property
    def units_str(self): ...
    @property
    def qty(self): ...
    def to_dict(self): ...

class CpuResource(Resource):
    def __init__(self, qty) -> None: ...

class RamResource(Resource):
    def __init__(self, qty) -> None: ...

class DiskResource(Resource):
    def __init__(self, qty) -> None: ...

class GpuResource(Resource):
    def __init__(self, qty) -> None: ...

class Resources:
    cpus: Incomplete
    ram: Incomplete
    disk: Incomplete
    gpus: Incomplete
    def __init__(self, cpus=..., ram=..., disk=..., gpus=...) -> None: ...
    def __eq__(self, other): ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, resources_dict: dict): ...
