from _typeshed import Incomplete
from airflow.compat.functools import cache as cache

IS_WINDOWS: Incomplete
log: Incomplete

def is_tty(): ...
def is_terminal_support_colors() -> bool: ...
def get_airflow_git_version(): ...
def getuser() -> str: ...
