import signal
from airflow.configuration import conf as conf
from airflow.exceptions import AirflowException as AirflowException
from typing import Generator

IS_WINDOWS: bool
DEFAULT_TIME_TO_WAIT_AFTER_SIGTERM: int
def reap_process_group(process_group_id: int, logger, sig: signal.Signals = ..., timeout: int = ...) -> dict[int, int]: ...
def execute_in_subprocess(cmd: list[str], cwd: str | None = ...) -> None: ...
def execute_in_subprocess_with_kwargs(cmd: list[str], **kwargs) -> None: ...
def execute_interactive(cmd: list[str], **kwargs) -> None: ...
def kill_child_processes_by_pids(pids_to_kill: list[int], timeout: int = ...) -> None: ...
def patch_environ(*args, **kwds) -> Generator[None, None, None]: ...
def check_if_pidfile_process_is_running(pid_file: str, process_name: str): ...
def set_new_process_group() -> None: ...
