from airflow.utils.process_utils import execute_in_subprocess as execute_in_subprocess

def remove_task_decorator(python_source: str, task_decorator_name: str) -> str: ...
def prepare_virtualenv(venv_directory: str, python_bin: str, system_site_packages: bool, requirements: list[str] | None = None, requirements_file_path: str | None = None, pip_install_options: list[str] | None = None, index_urls: list[str] | None = None) -> str: ...
def write_python_script(jinja_context: dict, filename: str, render_template_as_native_obj: bool = False): ...
