import typing
from typing import ClassVar

T: typing.TypeVar

class Singleton(type, typing.Generic):
    _instances: ClassVar[dict] = ...
    __orig_bases__: ClassVar[tuple] = ...
    __parameters__: ClassVar[tuple] = ...
    @classmethod
    def __call__(cls: Singleton[T], *args, **kwargs) -> T: ...
