from airflow.utils.session import create_session as create_session

TYPE_CHECKING: bool
def get_current_task_instance_session() -> Session: ...
def set_current_task_instance_session(*args, **kwds): ...
