import enum
from typing import ClassVar, Iterable

class WeekDay(enum.IntEnum):
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...
    MONDAY: ClassVar[WeekDay] = ...
    TUESDAY: ClassVar[WeekDay] = ...
    WEDNESDAY: ClassVar[WeekDay] = ...
    THURSDAY: ClassVar[WeekDay] = ...
    FRIDAY: ClassVar[WeekDay] = ...
    SATURDAY: ClassVar[WeekDay] = ...
    SUNDAY: ClassVar[WeekDay] = ...
    @classmethod
    def get_weekday_number(cls, week_day_str: str): ...
    @classmethod
    def convert(cls, day: str | WeekDay) -> int: ...
    @classmethod
    def validate_week_day(cls, week_day: str | WeekDay | Iterable[str] | Iterable[WeekDay]) -> set[int]: ...
    @classmethod
    def __init__(cls, value) -> None: ...
