import enum
from typing import ClassVar

class WeightRule(str, enum.Enum):
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[str]] = ...
    _value2member_map_: ClassVar[dict] = ...
    DOWNSTREAM: ClassVar[WeightRule] = ...
    UPSTREAM: ClassVar[WeightRule] = ...
    ABSOLUTE: ClassVar[WeightRule] = ...
    @classmethod
    def is_valid(cls, weight_rule: str) -> bool: ...
    @classmethod
    def all_weight_rules(cls, *args, **kwargs): ...
    def __format__(self, format_spec) -> str: ...
    @classmethod
    def __init__(cls, value) -> None: ...
