from airflow.configuration import conf as conf
from airflow.exceptions import AirflowException as AirflowException

LOG_LEVEL: str
FAB_LOG_LEVEL: str
LOG_FORMAT: str
DAG_PROCESSOR_LOG_FORMAT: str
LOG_FORMATTER_CLASS: str
COLORED_LOG_FORMAT: str
COLORED_LOG: bool
COLORED_FORMATTER_CLASS: str
DAG_PROCESSOR_LOG_TARGET: str
BASE_LOG_FOLDER: str
PROCESSOR_LOG_FOLDER: str
DAG_PROCESSOR_MANAGER_LOG_LOCATION: str
FILENAME_TEMPLATE: None
PROCESSOR_FILENAME_TEMPLATE: str
DEFAULT_LOGGING_CONFIG: dict
EXTRA_LOGGER_NAMES: str
DEFAULT_DAG_PARSING_LOGGING_CONFIG: dict
REMOTE_LOGGING: bool
