from _typeshed import Incomplete
from collections.abc import Generator

def get_mssql_table_constraints(conn, table_name) -> dict[str, dict[str, list[str]]]: ...
def disable_sqlite_fkeys(op) -> Generator[Incomplete]: ...
