import airflow.auth.managers.fab.api_endpoints.role_and_permission_endpoint as role_and_permission_endpoint
import airflow.auth.managers.fab.api_endpoints.user_endpoint as user_endpoint
from airflow.api_connexion.exceptions import BadRequest as BadRequest
from airflow.www.extensions.init_auth_manager import get_auth_manager as get_auth_manager

TYPE_CHECKING: bool
def get_role(*args, **kwargs): ...
def get_roles(*args, **kwargs): ...
def delete_role(*args, **kwargs): ...
def patch_role(*args, **kwargs): ...
def post_role(*args, **kwargs): ...
def get_permissions(*args, **kwargs): ...
def get_user(*args, **kwargs): ...
def get_users(*args, **kwargs): ...
def post_user(*args, **kwargs): ...
def patch_user(*args, **kwargs): ...
def delete_user(*args, **kwargs): ...
