from airflow.api_connexion.exceptions import BadRequest as BadRequest
from airflow.api_connexion.types import APIResponse as APIResponse
from airflow.providers.fab.auth_manager.api_endpoints import role_and_permission_endpoint as role_and_permission_endpoint, user_endpoint as user_endpoint
from airflow.www.extensions.init_auth_manager import get_auth_manager as get_auth_manager

def get_role(**kwargs) -> APIResponse: ...
def get_roles(**kwargs) -> APIResponse: ...
def delete_role(**kwargs) -> APIResponse: ...
def patch_role(**kwargs) -> APIResponse: ...
def post_role(**kwargs) -> APIResponse: ...
def get_permissions(**kwargs) -> APIResponse: ...
def get_user(**kwargs) -> APIResponse: ...
def get_users(**kwargs) -> APIResponse: ...
def post_user(**kwargs) -> APIResponse: ...
def patch_user(**kwargs) -> APIResponse: ...
def delete_user(**kwargs) -> APIResponse: ...
