import airflow.api_connexion.security as security
from airflow.api_connexion.endpoints.request_dict import get_json_request_dict as get_json_request_dict
from airflow.api_connexion.exceptions import AlreadyExists as AlreadyExists, BadRequest as BadRequest, NotFound as NotFound
from airflow.api_connexion.parameters import apply_sorting as apply_sorting, check_limit as check_limit, format_parameters as format_parameters
from airflow.api_connexion.schemas.pool_schema import PoolCollection as PoolCollection, pool_collection_schema as pool_collection_schema, pool_schema as pool_schema
from airflow.models.pool import Pool as Pool
from airflow.utils.session import provide_session as provide_session

TYPE_CHECKING: bool
NEW_SESSION: None
def delete_pool(*args, **kwargs) -> APIResponse: ...
def get_pool(*args, **kwargs) -> APIResponse: ...
def get_pools(*args, **kwargs) -> APIResponse: ...
def patch_pool(*args, **kwargs) -> APIResponse: ...
def post_pool(*args, **kwargs) -> APIResponse: ...
