from airflow.exceptions import AirflowBadRequest as AirflowBadRequest, PoolNotFound as PoolNotFound, RemovedInAirflow3Warning as RemovedInAirflow3Warning
from airflow.models import Pool as Pool
from airflow.utils.session import NEW_SESSION as NEW_SESSION, provide_session as provide_session
from sqlalchemy.orm import Session as Session

def get_pool(name, session: Session = ...): ...
def get_pools(session: Session = ...): ...
def create_pool(name, slots, description, session: Session = ...): ...
def delete_pool(name, session: Session = ...): ...
