from typing import ClassVar

TYPE_CHECKING: bool

class IsAuthorizedConnectionRequest(dict):
    __total__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class IsAuthorizedDagRequest(dict):
    __total__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class IsAuthorizedPoolRequest(dict):
    __total__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class IsAuthorizedVariableRequest(dict):
    __total__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
