TYPE_CHECKING: bool

class CallbackRequest:
    def __init__(self, full_filepath: str, processor_subdir: str | None = ..., msg: str | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str): ...

class TaskCallbackRequest(CallbackRequest):
    def __init__(self, full_filepath: str, simple_task_instance: SimpleTaskInstance, is_failure_callback: bool | None = ..., processor_subdir: str | None = ..., msg: str | None = ...) -> None: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str): ...

class DagCallbackRequest(CallbackRequest):
    def __init__(self, full_filepath: str, dag_id: str, run_id: str, processor_subdir: str | None, is_failure_callback: bool | None = ..., msg: str | None = ...) -> None: ...

class SlaCallbackRequest(CallbackRequest):
    def __init__(self, full_filepath: str, dag_id: str, processor_subdir: str | None, msg: str | None = ...) -> None: ...
