import airflow.security.permissions as permissions
from airflow.api_connexion.exceptions import AlreadyExists as AlreadyExists, BadRequest as BadRequest, NotFound as NotFound
from airflow.api_connexion.parameters import check_limit as check_limit, format_parameters as format_parameters
from airflow.api_connexion.schemas.role_and_permission_schema import ActionCollection as ActionCollection, RoleCollection as RoleCollection, action_collection_schema as action_collection_schema, role_collection_schema as role_collection_schema, role_schema as role_schema
from airflow.api_connexion.security import requires_access_custom_view as requires_access_custom_view
from airflow.auth.managers.fab.models import Action as Action, Role as Role
from airflow.utils.airflow_flask_app import get_airflow_app as get_airflow_app

TYPE_CHECKING: bool
NoContent: object
def get_role(*args, **kwargs) -> APIResponse: ...
def get_roles(*args, **kwargs) -> APIResponse: ...
def get_permissions(*args, **kwargs) -> APIResponse: ...
def delete_role(*args, **kwargs) -> APIResponse: ...
def patch_role(*args, **kwargs) -> APIResponse: ...
def post_role(*args, **kwargs) -> APIResponse: ...
