import airflow.security.permissions as permissions
from airflow.api_connexion.exceptions import AlreadyExists as AlreadyExists, BadRequest as BadRequest, NotFound as NotFound, Unknown as Unknown
from airflow.api_connexion.parameters import check_limit as check_limit, format_parameters as format_parameters
from airflow.api_connexion.schemas.user_schema import UserCollection as UserCollection, user_collection_item_schema as user_collection_item_schema, user_collection_schema as user_collection_schema, user_schema as user_schema
from airflow.api_connexion.security import requires_access_custom_view as requires_access_custom_view
from airflow.auth.managers.fab.models import User as User
from airflow.utils.airflow_flask_app import get_airflow_app as get_airflow_app

TYPE_CHECKING: bool
NoContent: object
def get_user(*args, **kwargs) -> APIResponse: ...
def get_users(*args, **kwargs) -> APIResponse: ...
def post_user(*args, **kwargs) -> APIResponse: ...
def patch_user(*args, **kwargs) -> APIResponse: ...
def delete_user(*args, **kwargs) -> APIResponse: ...
