import airflow.providers.docker.operators.docker
from airflow.exceptions import AirflowException as AirflowException
from airflow.providers.docker.operators.docker import DockerOperator as DockerOperator
from airflow.utils.strings import get_random_string as get_random_string
from typing import ClassVar

TYPE_CHECKING: bool

class DockerSwarmOperator(airflow.providers.docker.operators.docker.DockerOperator):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc_data] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def execute(self, context: Context) -> None: ...
    def on_kill(self) -> None: ...
