import datetime
import jinja2.nativetypes
import jinja2.sandbox
from _typeshed import Incomplete

class _AirflowEnvironmentMixin:
    def __init__(self, **kwargs) -> None: ...
    def is_safe_attribute(self, obj, attr, value): ...

class NativeEnvironment(_AirflowEnvironmentMixin, jinja2.nativetypes.NativeEnvironment): ...
class SandboxedEnvironment(_AirflowEnvironmentMixin, jinja2.sandbox.SandboxedEnvironment): ...

def ds_filter(value: datetime.date | datetime.time | None) -> str | None: ...
def ds_nodash_filter(value: datetime.date | datetime.time | None) -> str | None: ...
def ts_filter(value: datetime.date | datetime.time | None) -> str | None: ...
def ts_nodash_filter(value: datetime.date | datetime.time | None) -> str | None: ...
def ts_nodash_with_tz_filter(value: datetime.date | datetime.time | None) -> str | None: ...

FILTERS: Incomplete
