TYPE_CHECKING: bool
def on_task_instance_running(previous_state: TaskInstanceState | None, task_instance: TaskInstance, session: Session | None): ...
def on_task_instance_success(previous_state: TaskInstanceState | None, task_instance: TaskInstance, session: Session | None): ...
def on_task_instance_failed(previous_state: TaskInstanceState | None, task_instance: TaskInstance, session: Session | None): ...
