import airflow.security.permissions as permissions
import flask_appbuilder.security.views
import flask_babel.speaklater
from typing import ClassVar

class ActionModelView(flask_appbuilder.security.views.PermissionModelView):
    class_permission_name: ClassVar[str] = ...
    route_base: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
    list_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    show_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    add_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    edit_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    label_columns: ClassVar[dict] = ...

class PermissionPairModelView(flask_appbuilder.security.views.PermissionViewModelView):
    class_permission_name: ClassVar[str] = ...
    route_base: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
    list_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    show_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    add_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    edit_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    label_columns: ClassVar[dict] = ...
    list_columns: ClassVar[list] = ...

class ResourceModelView(flask_appbuilder.security.views.ViewMenuModelView):
    class_permission_name: ClassVar[str] = ...
    route_base: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
    list_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    show_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    add_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    edit_title: ClassVar[flask_babel.speaklater.LazyString] = ...
    label_columns: ClassVar[dict] = ...
