import airflow.security.permissions as permissions
import flask_appbuilder.security.views
from typing import ClassVar

class CustomRoleModelView(flask_appbuilder.security.views.RoleModelView):
    class_permission_name: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
