import airflow.security.permissions as permissions
import flask_appbuilder.security.views
from typing import ClassVar

class CustomUserStatsChartView(flask_appbuilder.security.views.UserStatsChartView):
    class_permission_name: ClassVar[str] = ...
    route_base: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
