import airflow.security.permissions as permissions
import flask_appbuilder.security.views
from typing import ClassVar

class CustomUserInfoEditView(flask_appbuilder.security.views.UserInfoEditView):
    class_permission_name: ClassVar[str] = ...
    route_base: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...

class CustomResetMyPasswordView(flask_appbuilder.security.views.ResetMyPasswordView):
    class_permission_name: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...

class CustomResetPasswordView(flask_appbuilder.security.views.ResetPasswordView):
    class_permission_name: ClassVar[str] = ...
    method_permission_name: ClassVar[dict] = ...
    base_permissions: ClassVar[list] = ...
